# Generated by Django 6.0.2 on 2026-02-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_booking_status_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
